apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyze
  template:
    metadata:
      labels:
        app: analyze
    spec:
      volumes:
      - name: all-configs
        projected:
          sources:
          - configMap:
              name: analyze-configs
          - configMap:
              name: common-configs
      containers:
      - name: analyze
        image: jklasa27/heartbeat:analyze
        imagePullPolicy: Always
        volumeMounts:
        - name: all-configs
          mountPath: /etc/config
        env:
        - name: LOG_LEVEL
          value: DEBUG
