remote_theme: just-the-docs/just-the-docs

title: "Heartbeat"
description: "JHU AI-Enabled Systems Project"
baseurl: "/heartbeat" # the subpath of your site, e.g. /blog
url: "https://jklasa.github.io" # the base hostname & protocol for your site, e.g. http://example.com

heading_anchors: false

footer_content: "2022 JHU Joel Klasa"
